function oscillation_plotEvents(ProbeInfo, probeSnippets)
% oscillation_plotEvents.m
%
% Description: Interactive viewer for probe-level events (prbEvent) - pages
%   through one prbEvent at a time, plotting every analyzed channel's
%   filtered signal for that event's window, in the same stacked/offset
%   shape as oshkosh_detect_funct.m's own "plot all events across channels"
%   figure (each channel plotted as trace(i) - offset*(i-1)), but showing
%   only the one event currently selected instead of a whole file's worth
%   of events at once. Left/right arrow keys move to the previous/next
%   event; up/down arrow keys cycle the color scheme used to color
%   channels, through two kinds of scheme:
%   (1) Shank (discrete/qualitative colormap: lines) -
%   every channel found in the same column of the same probe's
%   ProbeInfo.ProbeMaps entry gets the same color (columns are shanks per
%   ProbeInfo's own convention - see OpenEphys_BaseAnalysis.m).
%   (2) Depth (continuous colormap: copper) - within each shank, channels
%   are colored by their position along the shank (physical row order in
%   ProbeInfo.ProbeMaps, after excluding that probe's own
%   ProbeInfo.Ch_Remove channels and renumbering the remaining ones
%   starting at 1 - e.g. if a shank's first two physical rows are removed
%   channels, its next channel down becomes position 1), using the full
%   colormap range independently per shank (so "shallow" and "deep" mean
%   the same color on every shank, regardless of how many channels survive
%   removal on each one). Both shank assignment and depth position are
%   looked up per raw channel ID (from probeSnippets.chanals), not by the
%   row position within the snippet data - those are not guaranteed to be
%   in ProbeMaps/shank order. The stacked plot's vertical (line) order
%   also depends on the active scheme: under Shank, lines keep the
%   natural chanals order (already grouped by shank); under Depth, lines
%   are reordered so channels are grouped by depth position first and
%   shank second - e.g. every shank's position-1 channel plots together,
%   then every shank's position-2 channel, and so on - to make same-depth
%   activity across shanks easy to compare. Only the plotting order
%   changes; each line's color is still tied to its own channel identity.
%   NOTE (design calls made without re-confirming, since these are cheap
%   to change later): (1) takes probeSnippets instead of oscillations,
%   since probeSnippets is what actually carries the waveform data needed
%   to plot - oscillations isn't used here at all (no per-event metadata
%   like duration/during_stim is shown; easy to add as a further input if
%   wanted). (2) When probeSnippets covers more than one probe, all
%   probes' events are flattened into a single left/right-browsable
%   sequence in probe-then-index order (all of probe 1's events, then all
%   of probe 2's, etc.) - not interleaved chronologically across probes.
%
% Inputs:
%   ProbeInfo (struct) - this animal's ProbeInfo struct (see
%     oshkosh_detect_funct.m for field details). Used here for .ProbeMaps
%     (cell array, 1 x probenum; each cell a 2D matrix of raw channel IDs
%     shaped like the physical probe, columns = shanks, rows = physical
%     position along the shank) and .Ch_Remove (cell array, 1 x probenum;
%     per-probe raw channel IDs excluded for the depth color scheme's
%     position numbering).
%   probeSnippets (struct) - third output of oshkosh_detect_funct.m.
%     Used fields: .chanals, .probes, .event_data (cell, 1 x
%     length(probes); event_data{p}{k} is a [numel(chanals) x
%     window_length] filtered-signal matrix for probe p's k-th prbEvent).
%
% Outputs:
%   (none) - opens an interactive figure window. Scroll with left/right
%   (event) and up/down (color palette) arrow keys; close the figure to
%   stop.
%
% Dependencies: Expects probeSnippets to have been generated by
%   oshkosh_detect_funct.m using this SAME ProbeInfo (so probeSnippets.chanals
%   are valid raw channel IDs to look up in ProbeInfo.ProbeMaps).

if isempty(probeSnippets.probes)
    error('oscillation_plotEvents:NoProbes', 'probeSnippets has no probes.');
end

%% assign each channel (by raw channel ID, not row position) to a shank
chanals = probeSnippets.chanals;
nChan = numel(chanals);
shank_key = nan(nChan,2); % [probe index into ProbeMaps, column index within that probe's map]
for i = 1:nChan
    for pr = 1:numel(ProbeInfo.ProbeMaps)
        [~, col] = find(ProbeInfo.ProbeMaps{pr} == chanals(i));
        if ~isempty(col)
            shank_key(i,:) = [pr, col(1)];
            break
        end
    end
end
if any(isnan(shank_key(:)))
    error('oscillation_plotEvents:UnmappedChannel', ...
        'One or more channels in probeSnippets.chanals were not found in any ProbeInfo.ProbeMaps entry.');
end
[~, ~, shank_group] = unique(shank_key, 'rows'); % shank_group(i) = shank index (1..nShanks) for channel i
nShanks = max(shank_group);

%% position of each channel along its shank (depth), excluding that probe's Ch_Remove channels
depth_position = nan(nChan,1);
for i = 1:nChan
    pr = shank_key(i,1);
    col = shank_key(i,2);
    shank_col_ids = ProbeInfo.ProbeMaps{pr}(:,col); % physical row order = physical position along the shank
    kept_ids = shank_col_ids(~ismember(shank_col_ids, ProbeInfo.Ch_Remove{pr}));
    depth_position(i) = find(kept_ids == chanals(i), 1);
end
shank_max_pos = zeros(nShanks,1);
for s = 1:nShanks
    shank_max_pos(s) = max(depth_position(shank_group==s));
end

%% flatten every probe's events into one browsable sequence (probe-then-index order)
flat_pk = [];
for p = 1:numel(probeSnippets.probes)
    nEvents = numel(probeSnippets.event_data{p});
    flat_pk = [flat_pk; [repmat(p,nEvents,1), (1:nEvents)']];
end
if isempty(flat_pk)
    error('oscillation_plotEvents:NoEvents', 'probeSnippets has no detected probe events to plot.');
end

%% set up interactive figure
ud.probeSnippets = probeSnippets;
ud.shank_group = shank_group;
ud.nShanks = nShanks;
ud.depth_position = depth_position;
ud.shank_max_pos = shank_max_pos;
ud.flat_pk = flat_pk;
ud.nTotal = size(flat_pk,1);
ud.curIdx = 1;
ud.schemeMode = {'shank','depth'}; %parallel to schemeCmap
ud.schemeCmap = {'lines','copper'};
ud.cmapIdx = 1;

fig = figure('KeyPressFcn', @keypress, 'Name', 'oscillation_plotEvents');
ud.ax = axes('Parent', fig);
setappdata(fig, 'ud', ud);
redraw(fig);

end

function keypress(fig, evt)
    ud = getappdata(fig, 'ud');
    switch evt.Key
        case 'rightarrow'
            ud.curIdx = min(ud.curIdx + 1, ud.nTotal);
        case 'leftarrow'
            ud.curIdx = max(ud.curIdx - 1, 1);
        case 'uparrow'
            ud.cmapIdx = mod(ud.cmapIdx, numel(ud.schemeCmap)) + 1;
        case 'downarrow'
            ud.cmapIdx = mod(ud.cmapIdx - 2, numel(ud.schemeCmap)) + 1;
        otherwise
            return
    end
    setappdata(fig, 'ud', ud);
    redraw(fig);
end

function channel_colors = getChannelColors(ud)
    cmap_name = ud.schemeCmap{ud.cmapIdx};
    scheme_mode = ud.schemeMode{ud.cmapIdx};
    channel_colors = zeros(numel(ud.shank_group), 3);
    if strcmp(scheme_mode, 'shank')
        colors = feval(cmap_name, ud.nShanks);
        for i = 1:numel(ud.shank_group)
            channel_colors(i,:) = colors(ud.shank_group(i),:);
        end
    else %depth - full colormap range per shank, independent of other shanks' channel counts
        for s = 1:ud.nShanks
            idx = find(ud.shank_group == s);
            colors_s = feval(cmap_name, ud.shank_max_pos(s));
            for ii = 1:numel(idx)
                channel_colors(idx(ii),:) = colors_s(ud.depth_position(idx(ii)),:);
            end
        end
    end
end

function plot_order = getPlotOrder(ud)
    scheme_mode = ud.schemeMode{ud.cmapIdx};
    nCh = numel(ud.shank_group);
    if strcmp(scheme_mode, 'shank')
        plot_order = (1:nCh)'; %natural chanals order - already grouped by shank
    else %depth - grouped by depth position first, shank second, so same-depth channels plot together across shanks
        [~, plot_order] = sortrows([ud.depth_position, ud.shank_group, (1:nCh)']);
    end
end

function redraw(fig)
    ud = getappdata(fig, 'ud');
    p = ud.flat_pk(ud.curIdx,1);
    k = ud.flat_pk(ud.curIdx,2);
    snippet = ud.probeSnippets.event_data{p}{k};
    nCh = size(snippet,1);
    cmap_name = ud.schemeCmap{ud.cmapIdx};
    scheme_mode = ud.schemeMode{ud.cmapIdx};
    channel_colors = getChannelColors(ud);
    plot_order = getPlotOrder(ud);

    cla(ud.ax);
    hold(ud.ax, 'on');
    offset_step = 500;
    for slot = 1:nCh
        i = plot_order(slot);
        plot(ud.ax, snippet(i,:) - offset_step*(slot-1), 'Color', channel_colors(i,:));
    end
    hold(ud.ax, 'off');
    title(ud.ax, sprintf('Probe %d - event %d/%d  (overall %d/%d)  -  colors: %s (%s)', ...
        ud.probeSnippets.probes(p), k, numel(ud.probeSnippets.event_data{p}), ud.curIdx, ud.nTotal, scheme_mode, cmap_name), ...
        'Interpreter', 'none');
end
